services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d db
      interval: 3s
      timeout: 3s
      retries: 3
  
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    env_file:
      - .env
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
 
  backend:
    container_name: backend
    build: 
      context: .
    env_file:
    - .env
    ports:
      - ${APP_PORT}:${APP_PORT}
    entrypoint: poetry run backend
    depends_on:
      redis:
        condition: service_healthy
