services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    env_file:
      - .env
    command: -p 5433
    expose:
      - 5433
    volumes:
      - postgres_data:/var/lib/postgres
    healthcheck:
      test: ["CMD-SHELL", "psql -h localhost -p 5433 -U USER"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    restart: always
    command: --port 5370
    expose:
      - 5370

  backend:
    build: 
      context: .
    ports:
      - 8000:8000
    entrypoint: ./run-backend.sh
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

  parser:
    build: 
      context: .
    entrypoint:   ./run-parser.sh
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
 
volumes:
  postgres_data:
    driver: local