services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5433:5432
    env_file:
      - .env
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d db
      interval: 3s
      timeout: 3s
      retries: 3
  
  redis:
    container_name: redis
    image: redis:latest
    restart: always
    ports:
      - 5370:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 5
 
  backend:
    container_name: backend
    build: 
      context: .
    ports:
      - 8000:8000
    entrypoint: poetry run backend
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
